
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unisannio.assd;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-28T20:03:26.695+02:00
 * Generated source version: 3.5.1
 *
 */
public class PaymentServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://assd.unisannio.it/", "PaymentServiceImplService");
        QName portName = new QName("http://assd.unisannio.it/", "PaymentServiceImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:8080/Exercise_4.2/services/PaymentServiceImplPort");
        it.unisannio.assd.PaymentService client = service.getPort(portName,  it.unisannio.assd.PaymentService.class);
        System.out.println(client.getSupportedCreditCards());
        // Insert code to invoke methods on the client here
    }

}