
package it.unisannio.assd;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-28T20:03:26.615+02:00
 * Generated source version: 3.5.1
 *
 */

public class PaymentServiceServer{

    protected PaymentServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new it.unisannio.assd.PaymentServiceImpl();
        String address = "http://localhost:9090/PaymentServiceImplPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new PaymentServiceServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

